package jamgmilk.fuwagit.ui.theme

import androidx.compose.ui.graphics.Color

/* Kawaii Mizuiro palette START */
val primaryLight = Color(0xFF34618D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD0E4FF)
val onPrimaryContainerLight = Color(0xFF164974)
val secondaryLight = Color(0xFF526070)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD6E4F7)
val onSecondaryContainerLight = Color(0xFF3B4857)
val tertiaryLight = Color(0xFF6A5779)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF1DAFF)
val onTertiaryContainerLight = Color(0xFF514060)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8F9FF)
val onBackgroundLight = Color(0xFF191C20)
val surfaceLight = Color(0xFFF8F9FF)
val onSurfaceLight = Color(0xFF191C20)
val surfaceVariantLight = Color(0xFFDFE3EB)
val onSurfaceVariantLight = Color(0xFF42474E)
val outlineLight = Color(0xFF73777F)
val outlineVariantLight = Color(0xFFC2C7CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3135)
val inverseOnSurfaceLight = Color(0xFFEFF0F7)
val inversePrimaryLight = Color(0xFF9ECAFC)
val surfaceDimLight = Color(0xFFD8DAE0)
val surfaceBrightLight = Color(0xFFF8F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F3F9)
val surfaceContainerLight = Color(0xFFECEEF4)
val surfaceContainerHighLight = Color(0xFFE6E8EE)
val surfaceContainerHighestLight = Color(0xFFE0E2E8)

val diffAddedBackgroundLight = Color(0xFFDCFFDC)
val diffAddedTextLight = Color(0xFF1A7F37)
val diffDeletedBackgroundLight = Color(0xFFFFE0E0)
val diffDeletedTextLight = Color(0xFFCF222E)
val diffAddedHighlightLight = Color(0xFF80C982)
val diffDeletedHighlightLight = Color(0xFFFF8181)
val diffAddedInlineBackgroundLight = Color(0xFFB4FFB4)
val diffDeletedInlineBackgroundLight = Color(0xFFFFB3B3)

val primaryDark = Color(0xFF9ECAFC)
val onPrimaryDark = Color(0xFF003256)
val primaryContainerDark = Color(0xFF164974)
val onPrimaryContainerDark = Color(0xFFD0E4FF)
val secondaryDark = Color(0xFFBAC8DB)
val onSecondaryDark = Color(0xFF243140)
val secondaryContainerDark = Color(0xFF3B4857)
val onSecondaryContainerDark = Color(0xFFD6E4F7)
val tertiaryDark = Color(0xFFD5BEE5)
val onTertiaryDark = Color(0xFF3A2948)
val tertiaryContainerDark = Color(0xFF514060)
val onTertiaryContainerDark = Color(0xFFF1DAFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101418)
val onBackgroundDark = Color(0xFFE0E2E8)
val surfaceDark = Color(0xFF101418)
val onSurfaceDark = Color(0xFFE0E2E8)
val surfaceVariantDark = Color(0xFF42474E)
val onSurfaceVariantDark = Color(0xFFC2C7CF)
val outlineDark = Color(0xFF8C9199)
val outlineVariantDark = Color(0xFF42474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E2E8)
val inverseOnSurfaceDark = Color(0xFF2D3135)
val inversePrimaryDark = Color(0xFF34618D)
val surfaceDimDark = Color(0xFF101418)
val surfaceBrightDark = Color(0xFF36393E)
val surfaceContainerLowestDark = Color(0xFF0B0E12)
val surfaceContainerLowDark = Color(0xFF191C20)
val surfaceContainerDark = Color(0xFF1D2024)
val surfaceContainerHighDark = Color(0xFF272A2F)
val surfaceContainerHighestDark = Color(0xFF32353A)

val diffAddedBackgroundDark = Color(0xFF1B3D1B)
val diffAddedTextDark = Color(0xFF73D497)
val diffDeletedBackgroundDark = Color(0xFF3D1B1B)
val diffDeletedTextDark = Color(0xFFFF7B7B)
val diffAddedHighlightDark = Color(0xFF4CAF50)
val diffDeletedHighlightDark = Color(0xFFE57373)
val diffAddedInlineBackgroundDark = Color(0xFF2E7D32)
val diffDeletedInlineBackgroundDark = Color(0xFFC62828)
/* Kawaii Mizuiro palette END */
